### ISSUE TITLE
Documentation of matrix section doesn't reflect the behavior

### ISSUE THREAD

**Issue by mcyprian** [devexp-db/distgen#80]
[Distgen documentation of multispec](http://distgen.readthedocs.io/en/latest/spec_multispec.html#multispecs) contains following matrix section example:
```
matrix:
  exclude:
    - distros:
        - fedora-26-x86_64
      version: 2.2
```
Matrix section like this won't exclude any combinations, because version number 2.2 (type float) is compared to "2.2" (type str) inside **verify_selectors** method. The only correct syntax at this moment is following:
```
matrix:
  exclude:
    - distros:
        - fedora-26-x86_64
      version: "2.2"
```

Not sure if this should be fixed in documentation or the implementation of comparison should be more general to accept both options.

**Comment by mcyprian** [comment]
It can be easily reproduced using multispec example from the documentation:
```
...
  version:
    "2.2":
      version: "2.2"
    "2.4":
      version: "2.4"

# in the "matrix" section, you can specify combinations that you want
# to explicitly exclude from the rendering matrix
matrix:
  exclude:
    - distros:
        - fedora-26-x86_64
      version: 2.2
```
When I run `$ dg --multispec multispec.yml --multispec-combinations`
output is:
```
--distro centos-7-x86_64.yaml --multispec-selector version=2.2
--distro centos-7-x86_64.yaml --multispec-selector version=2.4
--distro fedora-26-x86_64.yaml --multispec-selector version=2.2
--distro fedora-26-x86_64.yaml --multispec-selector version=2.4
--distro fedora-25-x86_64.yaml --multispec-selector version=2.2
--distro fedora-25-x86_64.yaml --multispec-selector version=2.4
```
distro fedora-26  version=2.2 is present
It is necessary to add quotes to version in exclude part:
```
...
  version:
    "2.2":
      version: "2.2"
    "2.4":
      version: "2.4"

# in the "matrix" section, you can specify combinations that you want
# to explicitly exclude from the rendering matrix
matrix:
  exclude:
    - distros:
        - fedora-26-x86_64
      version: "2.2"
```
To get the correct output:
```
--distro centos-7-x86_64.yaml --multispec-selector version=2.2
--distro centos-7-x86_64.yaml --multispec-selector version=2.4
--distro fedora-26-x86_64.yaml --multispec-selector version=2.4
--distro fedora-25-x86_64.yaml --multispec-selector version=2.2
--distro fedora-25-x86_64.yaml --multispec-selector version=2.4
```
distro fedora-26  version=2.2 is excluded.
